FROM jboss/keycloak:12.0.1
ENV KEYCLOAK_IMPORT=/tmp/realm-export.json
ENV KEYCLOAK_USER=admin
ENV KEYCLOAK_PASSWORD=admin
ENV DB_VENDOR=mysql
ENV DB_ADDR=conftracker-db
ENV DB_DATABASE=conftracker
ENV DB_USER=conftracker
ENV DB_PASSWORD=conftracker
EXPOSE 8080
COPY ./realm-export.json /tmp/realm-export.json