FROM node:14
WORKDIR /opt/app
ENV PORT=3001
ENV MYSQL_USER=conftracker
ENV MYSQL_PASSWORD=conftracker
ENV MYSQL_DATABASE=conftracker
ENV MYSQL_HOST=conftracker-db
EXPOSE 3001
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
ENTRYPOINT ["npm", "start"]